@extends('layouts.master')
@section('title', 'History')
@section('content')
<section class="mt-5">
    <h2 class="fw-bold text-center text-uppercase">
        Our History
    </h2>
    <h4 class="fw-bold text-info mt-3">Barangay 386</h4>
    <p class="paragraph"> &emsp; &emsp; Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem minima aperiam tempora, asperiores facilis dolorem porro cupiditate amet fuga? Ducimus asperiores recusandae necessitatibus delectus ratione tenetur omnis error, excepturi, assumenda, eligendi ipsam praesentium non aut accusantium! Rem doloribus eaque laboriosam ipsa necessitatibus harum fugiat cupiditate dolores aliquid, voluptates repudiandae minima maxime eveniet numquam. A ipsa, vel reiciendis mollitia expedita labore blanditiis assumenda. Eveniet ullam pariatur assumenda hic nostrum necessitatibus tenetur deleniti quas doloribus laudantium inventore, expedita ab quaerat corporis! Quibusdam a libero animi modi reiciendis! Doloremque harum, suscipit aperiam quos pariatur laborum vitae deserunt eius nulla minus cum ipsum eos.</p>
    <h4 class="fw-bold text-info mt-3">Toponymy</h4>
    <p class="paragraph"> &emsp; &emsp; Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, exercitationem nostrum? Cum sapiente laudantium dolores animi omnis reprehenderit quaerat nihil quos voluptate veniam iste hic sunt beatae delectus, ullam vero architecto molestias aspernatur. Tempore debitis a, sit nihil voluptates neque, totam accusantium doloribus aspernatur, nulla pariatur distinctio animi cum fuga quaerat quas laborum! Vero nemo harum nulla provident! Ab inventore, temporibus soluta animi, odio deleniti accusamus quos eum debitis voluptate voluptatibus. Eligendi atque vitae deleniti.</p>
    <h4 class="fw-bold text-info mt-3">Modern History</h4>
    <p class="paragraph"> &emsp; &emsp; Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt rerum, mollitia aut facere voluptates iusto doloribus deserunt eos aliquam perferendis harum molestiae dolorem ipsum blanditiis, maxime excepturi possimus? Ducimus ipsam nesciunt saepe dolorum placeat voluptatem deserunt obcaecati? Modi, dolore quod! Totam, veniam aspernatur! Doloremque a reiciendis tenetur fuga adipisci vero voluptates voluptatum iusto mollitia animi. Non blanditiis officiis nostrum ducimus totam rem, repellat sequi, id ab sapiente quia reiciendis aut rerum, soluta laboriosam cumque voluptatem facilis! Nam corporis provident repudiandae culpa, ad voluptatum consectetur deserunt quasi aliquam pariatur possimus cupiditate quas id est tempore perferendis quo assumenda autem voluptatibus quos officiis sint temporibus similique! Consequuntur at iure dolore repudiandae, adipisci maxime minima. Nemo at similique modi illo neque dignissimos quibusdam hic alias temporibus, distinctio tempora ab quo excepturi doloremque, eaque quae nisi odit molestiae explicabo velit corrupti ut! Blanditiis, voluptatem tenetur debitis accusantium soluta incidunt corrupti reprehenderit nostrum odit voluptatum.</p>
    <h4 class="fw-bold text-info mt-3">Cityhood</h4>
    <p class="paragraph"> &emsp; &emsp; Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat provident, inventore possimus placeat ipsam accusantium quia nostrum quidem accusamus maiores officiis veritatis! Quis facere a pariatur, illo unde nam harum, doloremque reprehenderit, deserunt voluptatibus doloribus magni beatae. Quis perferendis eligendi, similique error quidem voluptate dignissimos explicabo doloremque quos reprehenderit autem ut nostrum, fugiat in suscipit at ipsa eaque iste cupiditate voluptas nobis tempora ipsum laudantium dicta! Voluptatum sint temporibus pariatur nulla dignissimos eveniet amet vero totam repudiandae dicta sit magni fugit cum nostrum, quo, cumque saepe? Exercitationem aliquid facilis iure corporis animi qui? Corrupti, illo saepe harum dolores in eius.</p>
    <h4 class="fw-bold text-info mt-3">Geography</h4>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1147.8994197900433!2d120.9867468864862!3d14.595769258570948!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397ca1d8a685e23%3A0xd497830ab5bc8241!2s385%2C%20Quiapo%2C%20Manila%2C%201008%20Metro%20Manila!5e0!3m2!1sen!2sph!4v1662505685509!5m2!1sen!2sph" width="625" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    <p class="paragraph">&emsp; &emsp; Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae accusamus eos ullam cumque similique impedit provident, laborum repudiandae repellendus, aperiam maiores eaque, cum ducimus sequi sapiente. Dolores, soluta. Ipsum a deserunt assumenda culpa libero commodi neque sapiente sed enim earum! Aliquam, suscipit, error alias maiores vel saepe aperiam accusantium, ducimus labore eveniet obcaecati ut aliquid quos. Praesentium, provident? Blanditiis porro commodi nisi veritatis saepe? Optio itaque incidunt eum! Eos dignissimos, labore nihil hic molestiae neque.</p>
</section>
@endsection